# -*- coding: utf-8 -*-

SETTINGS_NAME = "AdaplinTool"

DEFAULT_TOLERANCE = 5.0
DEFAULT_TIGHTNESS = 3.0
DEFAULT_STRIDE = 5.0
DEFAULT_VERTICES = 5
DEFAULT_SNAPPER_DISTANCES = 5.0
DEFAULT_SNAPPER_MODE = 0